### ISSUE TITLE
Why converting icons to symbolic icons?

### ISSUE THREAD

**Issue by andia89** [leoheck/numix-calibre#2]
I would argue that the icons are nice when they are colourful. Why are you converting them to symbolic icons (if you want to use symbolic icons you should use symbolic icons after all)?

But it's just a personal opinion...

**Comment by leoheck** [comment]
I do not understand your question. Calibre icon theme and GUI appearance don't fit into my desktop environment. This repository is just a test to make it suck less using numix icons. The icons can be coloured, it doesn't matter. By now, this is repository just a test. The fact is, I hate the original Calibre icon theme and its interface (in any OS). But I could not find an alternative to Calibre.

**Comment by andia89** [comment]
Ah ok so you haven't added icons yet? A lot of the icons in this repository are coloured `#bebebe` whereas they are coloured in the original Numix icon theme.

I agree that calibre looks shitty. Unfortunately the developer does not allow to use system icons (I have reported that, but it was marked as wontfix)

**Comment by leoheck** [comment]
I think we should start creating new beautiful (coloured) icons for calibre :). However, this will take a lot of time. I was also looking a way to patch calibre to use numix-theme (gtk and icons). So in this way we can put the icons in numix-theme and just apply the patch to make it nice. What do you think?

**Comment by andia89** [comment]
yeah that would be ideal... We can look through the icons here, and make a list for which icons we need a new one. There are a lot of icons already in the theme we can use

**Comment by leoheck** [comment]
Yeah, the icons i choose are all from the numix. I will put a list here of all icons to be made (found). Can you help me to match them with numix icons and determine which one is missing? Also, some icons should be renamed. So this can be made with the patch. Actually I will create a new issue.

**Comment by andia89** [comment]
Sure.

**Comment by leoheck** [comment]
Done, issue https://github.com/leoheck/numix-calibre/issues/3

**Comment by andia89** [comment]
Closing this
